### ISSUE TITLE
[Question] Table 1 results - Datasets

### ISSUE THREAD

**Issue by yukioichida** [yakazimir/semantic_fragments#3]
Hi,

I have some questions about the results at the bottom of table 1. 

- I downloaded the dataset for the lossless inoculation but which dataset (hard, simple, brazil_fragment, final_test) were used to achieve the results at the bottom fo table 1?

- Where can I find the respective semantic fragment of each pair contained in inoculate directory (challenge_train.tsv)?

**Comment by yakazimir** [comment]
Hi @yukioichida , 

Apologies for the confusion, I see the issue here (this is a restructured version of an older repo). The main datasets are at `top/level/data` (see [README](https://github.com/yakazimir/semantic_fragments/tree/master/data) there for details). Earlier these datasets were under `generate_challenge` (there are still some scripts with this target, which is probably causing some of the confusion; `hard` => `data/monotonicity_hard`, `easy` => `data/monotonicity_easy`, `brazil_fragments/simple_negation_only` => `data/negation` etc.. I will fix the scripts with this confusion).   

You should be able to see the (correct) way to reproduce the test results from the Table 1 [here](https://github.com/yakazimir/semantic_fragments/blob/master/scripts/tests_inoculation.sh), which will point to the correct data in the repo. I haven't released the full inoculation sets (they are just cut-up versions of the training sets so they can be built easy from the data there.. there are all the `.json` version for the allennlp models, you will notice that some of these are smaller training sets, since these models obtained better results/less forgetting using smaller sets as revealed through the inoculation experiments).

**Comment by yukioichida** [comment]
Thank you for your quick answer. No problem at all.

I had read the script with sketch of all datasets, but I could not figure out how to reproduce the results at the bottom of Table 1.
Actually, I am trying only to reproduce the final results, ignoring the inoculate set. I think that your reply already helped me to understand better.

Thanks for your explanation. I will close this issue.

**Comment by yakazimir** [comment]
I just posted a version of the original test data in `generate_challenge/final_tests.zip` (and noticed a small mistake in how the `monotonicity_hard/test/challenge_dev.tsv` was copied over, so hopefully understanding the script and the exact data it involves should make more sense now.
